### ISSUE TITLE
typedSql doesn't work with replicas unless replica / primary is specified

### ISSUE THREAD

**Issue by drewhamlett** [prisma/extension-read-replicas#38]
```ts
  const users = await db
    .$queryRawTyped(findUser(accessToken))
```

Throws error

```
TypeError: Cannot read properties of undefined (reading 'map')
    at ll (/Users/project/node_modules/@prisma/client/runtime/library.js:114:14239)
    at Mt (/Users/project/node_modules/@prisma/client/runtime/library.js:114:14184)
    at /Users/project/node_modules/@prisma/client/runtime/library.js:121:292
    at Proxy._executeRequest (/Users/project/node_modules/@prisma/client/runtime/library.js:130:10111)
```

Works:

 ```ts
  const users = await db
    .$replica()
    .$queryRawTyped(findUser(accessToken))
```

Thanks!

**Comment by dennypradipta** [comment]
+1 for this. I have to query using $queryRawTyped.

```typescript
ctx.prisma.$queryRawTyped(queryEventIdByIncident(wildSearchWord)),
```

This leads to linting problems. But if I do this

```
            ctx.prisma
              // @ts-ignore
              .$replica()
              .$queryRawTyped(queryEventIdByIncident(wildSearchWord)),
```

It works. Also the @ts-ignore is related to #23

**Comment by bimusiek** [comment]
I wish I found this issue sooner, same problem for us. 
Still happens on prisma `5.22.0` with both `0.3.0` and `0.4.0` read replicas package.
