### ISSUE TITLE
Update package to work with prisma 6

### ISSUE THREAD

**Issue by shadoworion** [prisma/extension-read-replicas#41]
Update package to work with prisma 6

```
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: backend@1.0.0
npm error Found: @prisma/client@6.0.1
npm error node_modules/@prisma/client
npm error   @prisma/client@"6.0.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @prisma/client@"^5.2.0" from @prisma/extension-read-replicas@0.4.0
npm error node_modules/@prisma/extension-read-replicas
npm error   @prisma/extension-read-replicas@"0.4.0" from the root project
```

**Comment by clemens** [comment]
PR is here: https://github.com/prisma/extension-read-replicas/pull/42. You could test it and upvote it if it works for you. :-)

**Comment by shadoworion** [comment]
From prisma 6.2+ it's not working at all.

```bash
TypeError: Cannot read properties of undefined (reading 'findFirst')
    at Array.$allOperations (/backend/node_modules/@prisma/extension-read-replicas/dist/index.js:146:34)
    at /backend/node_modules/@prisma/client-postgresql/runtime/library.js:31:9170
    at i (/backend/node_modules/@prisma/client-postgresql/runtime/library.js:121:1016)
    at PrismaPromise.then (/backend/node_modules/@prisma/client-postgresql/runtime/library.js:121:1091)
```

**Comment by lukebelbina** [comment]
Can confirm this is not working on prisma 6.2.1

**Comment by meotimdihia** [comment]
TypeError: Cannot read properties of undefined (reading 'groupBy')

**Comment by yharaskrik** [comment]
For anyone running into issues with >= Prisma 6.2, you can get around it by initializing PrismaClients with the constructor and passing them into the extension as replicas, rather than `urls`.

```typescript
    return client
        .$extends(
            readReplicas({
                replicas: (readonlyUrls ?? []).map((url) => new PrismaClient({ datasourceUrl: url })),
            })
        );
```

**Comment by nurul3101** [comment]
Hey everyone!

We released a new version of read-replicas extension - `0.4.1`.

https://www.npmjs.com/package/@prisma/extension-read-replicas

Can you please upgrade to the latest version and confirm if the issue is resolved?

**Comment by meotimdihia** [comment]
I confirm the problem was solved. I am using it on high-traffic production.

**Comment by meotimdihia** [comment]
@nurul3101 I confirm the problem was solved. I am using it on high-traffic production.
